const HEIGHT = 35;
const WIDTH = 61;

const SPEED = 0.4;
const COLLISION_STEPS = 5;

const BRICK_COLS = 4;
const BRICK_ROWS = 3;

const SPAWN_FREQUENCY = 10000;
const SPAWN_DURATION = 10000;

module.exports = {
  HEIGHT,
  WIDTH,
  SPEED,
  COLLISION_STEPS,
  BRICK_COLS,
  BRICK_ROWS,
  SPAWN_FREQUENCY,
  SPAWN_DURATION
};
